version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: local
      TZ: 'UTC'
    volumes:
      - db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"


  web:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db